FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

# Set environment variables for Android SDK, NDK, and paths
ENV ANDROID_SDK_ROOT=/opt/android-sdk
ENV ANDROID_NDK_ROOT=$ANDROID_SDK_ROOT/ndk/21.4.7075529
ENV ANDROID_HOME=$ANDROID_SDK_ROOT
ENV ANDROID_BUILD_TOOLS=$ANDROID_SDK_ROOT/build-tools/30.0.0

RUN apt-get update
RUN apt-get install -y --no-install-recommends \
    software-properties-common \
    gnupg2 \
    ca-certificates

# Add apt-fast for much faster downloads
RUN add-apt-repository ppa:apt-fast/stable -y
RUN apt-get update -y
RUN apt-get install -y apt-fast

# Setup build tools needed
RUN apt-fast install -y \
    build-essential \
    libgl1-mesa-dev \
    libgstreamer-gl1.0-0 \
    libpulse-dev \
    libxcb-glx0 \
    libxcb-icccm4 \
    libxcb-image0 \
    libxcb-keysyms1 \
    libxcb-randr0 \
    libxcb-render-util0 \
    libxcb-render0 \
    libxcb-shape0 \
    libxcb-shm0 \
    libxcb-sync1 \
    libxcb-util1 \
    libxcb-xfixes0 \
    libxcb-xinerama0 \
    libxcb1 \
    libxkbcommon-dev \
    libxkbcommon-x11-0 \
    libxcb-xkb-dev \
    ccache \
    openjdk-11-jdk \
    unzip \
    python3-pip \
    wget \
    locales \
    git

RUN python3 -m pip install setuptools wheel py7zr==0.20.*
RUN python3 -m pip install aqtinstall==3.1.*

# Set JAVA_HOME and update PATH
ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
ENV SKIP_JDK_VERSION_CHECK=TRUE

# Install Android SDK and NDK
RUN mkdir -p $ANDROID_SDK_ROOT/cmdline-tools/latest && \
    wget https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip -O /opt/cmdline-tools.zip && \
    unzip /opt/cmdline-tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools && \
    mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools/* $ANDROID_SDK_ROOT/cmdline-tools/latest/ && \
    rm -rf $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools && \
    rm /opt/cmdline-tools.zip && \
    yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses && \
    $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools" "platforms;android-33" "build-tools;30.0.0" "ndk;21.4.7075529"

# Qt setup and environment variables
ENV QT_VERSION="5.15.2"
ENV QT_PATH="/opt/Qt"
ENV QT_HOST="linux"
ENV QT_HOST_ARCH="linux_gcc_64"
ENV QT_HOST_ARCH_DIR="gcc_64"
ENV QT_TARGET="android"
ENV QT_TARGET_ARCH_ARMV7="android_armv7"
ENV QT_TARGET_ARCH_ARM64="android_arm64_v8a"
ENV QT_MODULES="qtcharts"

# Install aqtinstall and download Qt for both host and target architectures
RUN python3 -m pip install aqtinstall && mkdir -p $QT_PATH
RUN aqt install-qt $QT_HOST $QT_TARGET $QT_VERSION $QT_TARGET -O $QT_PATH -m $QT_MODULES -b https://mirrors.ocf.berkeley.edu/qt/

RUN ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --list_installed | \
    grep "platforms;android-" | \
    grep -v "platforms;android-33 " | \
    awk '{print $1}' | \
    xargs -I {} ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --uninstall "{}"

# Set Qt-related environment variables for ARMv7 and ARM64 architectures
ENV QT_ROOT_DIR_ARMV7=$QT_PATH/$QT_VERSION/$QT_TARGET_ARCH_ARMV7
ENV QT_ROOT_DIR_ARM64=$QT_PATH/$QT_VERSION/$QT_TARGET_ARCH_ARM64
ENV QT_HOST_PATH=$QT_PATH/$QT_VERSION/$QT_HOST_ARCH_DIR
ENV QT_PLUGIN_PATH_ARMV7=$QT_ROOT_DIR_ARMV7/plugins
ENV QT_PLUGIN_PATH_ARM64=$QT_ROOT_DIR_ARM64/plugins
ENV QML2_IMPORT_PATH_ARMV7=$QT_ROOT_DIR_ARMV7/qml
ENV QML2_IMPORT_PATH_ARM64=$QT_ROOT_DIR_ARM64/qml
ENV PKG_CONFIG_PATH_ARMV7=$QT_ROOT_DIR_ARMV7/lib/pkgconfig:$PKG_CONFIG_PATH
ENV PKG_CONFIG_PATH_ARM64=$QT_ROOT_DIR_ARM64/lib/pkgconfig:$PKG_CONFIG_PATH
ENV LD_LIBRARY_PATH_ARMV7=$QT_ROOT_DIR_ARMV7/lib:$LD_LIBRARY_PATH
ENV LD_LIBRARY_PATH_ARM64=$QT_ROOT_DIR_ARM64/lib:$LD_LIBRARY_PATH

# Consolidate PATH settings
ENV PATH=$JAVA_HOME/bin:/usr/lib/ccache:$QT_HOST_PATH/bin:$QT_ROOT_DIR_ARMV7/bin:$QT_ROOT_DIR_ARM64/bin:$PATH:$ANDROID_SDK_ROOT/tools:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_BUILD_TOOLS:$ANDROID_NDK_ROOT

RUN locale-gen en_US.UTF-8 && update-locale LANG=en_US.UTF-8

RUN git config --global --add safe.directory /project/source

# Set working directory
WORKDIR /project/build

ENV QT_ANDROID_KEYSTORE_PATH=/project/source/android/android_release.keystore
ENV QT_ANDROID_KEYSTORE_ALIAS="qgc-mrq"
ENV QT_ANDROID_KEYSTORE_STORE_PASS="12345678"
ENV QT_ANDROID_KEYSTORE_KEY_PASS="12345678"
ENV QT_ANDROID_ABIS="arm64-v8a"

ENV ANDROID_KEYSTORE_PASSWORD: "12345678"
ENV ANDROID_NDK_ROOT: $ANDROID_SDK_ROOT/ndk/21.4.7075529
ENV ANDROID_NDK_HOME: $ANDROID_SDK_ROOT/ndk/21.4.7075529
ENV ANDROID_NDK_LATEST_HOME: $ANDROID_SDK_ROOT/ndk/21.4.7075529
ENV ANDROID_NDK: $ANDROID_SDK_ROOT/ndk/21.4.7075529

# NOTE: if it gives and error for no dialect 'All' in MAVLink, run 'git submodule update --init --recursive' if you haven't
CMD cd /project/build/ && \
    /opt/Qt/5.15.2/android/bin/qmake -r /project/source/qgroundcontrol.pro -spec android-clang CONFIG+=StableBuild CONFIG+=installer ANDROID_ABIS="${QT_ANDROID_ABIS}" && \
    make -j$(nproc)




